"""empty message

Revision ID: 58bce2a9b377
Revises: 0cf6df69a111
Create Date: 2024-06-03 17:40:26.763223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bce2a9b377'
down_revision = '0cf6df69a111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
